name: '{{parameters.spec.stack.name}}'
services:
  {{parameters.metadata.name}}Db:
    image: postgres:{{parameters.spec.version}}
    environment:
      POSTGRES_DB: '{{parameters.metadata.name}}'
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  {{parameters.metadata.name}}Adminer:
    image: 'adminer'
    restart: always
    ports:
      - 8080:8080